# TensorFlow Fundamentals
*********************************************************

- Starting this notebook to follow along with the udemy tutorial.
- I named this notebook the same name as the provided course work, but added a p at the end of the number in the title to indicate to the vimwiki_load script that this is a personal version and I want to upload this particular version to my vimwiki.

- In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.
- Specifically we're going to cover:
    - Intro to tensors
    - Getting info from tensors
    - Manipulating tensors
    - Tensors & NumPy
    - Using @tf.function (a way to speed up your regular Python functions)
    - Using GPUs with TensorFlow (or TPUs)
    - Exercises to try for yourself!!

### Intro to Tensors

In [104]:
import tensorflow as tf
print(tf.__version__)

2.10.0


- Create a tensor with constant.

In [105]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

- Get the dimensions of a tensor.

In [106]:
scalar.ndim

0

- Create a vector.
    - Note we passed a python list.

In [107]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

- Get the dimension of a vector (which remember is still a constant).

In [108]:
vector.ndim

1

- Create a matrix.

In [109]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [110]:
matrix.ndim

2

- Using different data types.
- When creating a constant tensor, by default, we are using the int32 for our data type.
- We can use another type like float 16 and use different data types.
- This is imporant to know, because by chaning the dtype keyword argument, you can change the type of data being stored, which may come in handy for debugging.

In [111]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [112]:
another_matrix.ndim

2

In [113]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [114]:
tensor.ndim

3

- Essencially, when referring to tensors we are referring to any object that is a tensor object in TensorFlow. Even if the tensor object is only a 0 dimensional scalar, in TensorFlow, it's still referred to as a tensor.
- What have we created?
    - Scalar = a single number.
    - Vector = a number with a direction.
    - Matrix = a 2 dimensional array of numbers.
    - Tensor = a n-dimensinal array of numbers (where n can be any number)
        - 0 dimension is a scalar; 2 dimension is an matrix.

### Creating tensors with tf.Variable

- Create a variable tensor and a constant tensor and compare and contrast them.

In [115]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [116]:
# Does not work
# changeable_tensor[0] = 7
# Works
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [117]:
# Does not work
# unchangeable_tensor[0] = 7
# Still does not work
# unchangeable_tensor[0].assign(7)
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

### Creating random tensors

- Random tensors are tensors of some arbitrary size which contain random numbers.

In [118]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling the order of tensors

- Why shuffle the order of values in a tensor?
    - If the tensor represents our data like a group of pictures, if the pictures are ordered in any significant way, then that could teach the neural network with some sort of bias for items in the beginning of the list if it's not uniform.
    - We can shuffle the data so that it is as close to random as possible so we get try to eliminate any sort of bias towards items in the beginning of the list.
- Shuffle data so that inherant order doesn't affect learning.

In [119]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

2

- Using the shuffle function lets us shuffle the elements of the tensor along the first dimension.
- This means that the second dimension is left unaffected.

In [120]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

- Note that even if we set the seed for the shuffle, we still get different results each time we use the shuffle command.

In [121]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

- This is because the shuffle actaully depends on 2 random seeds, a global level seed and an operation level seed.
- When we set the global and the operation level seeds to the same thing, now we see the values no not change.

In [122]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

- Lesson: Read through TensorFlow documentation on tf.random.set_seed

- Big take away: If you want to shuffle your data in a reproducable way, you'll need to set both the global and operational seeds.

### Creating tensors from NumPy arrays

- TensorFlow has many of the same array operations as numpy. 

In [123]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [124]:
# Either of these ways work
tf.zeros([10, 7])
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

- You can also turn array from NumPy into tensors.
- The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (which is much faster for numerical computing).

In [125]:
# Create a NumPy array
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix)  # Capital for matrix or tensor.
# y = tf.constant(vector)       # Lowercase for vector.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [126]:
# Convert our NumPy array to a tensor.
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

- We cannot reshape our tensor like we can in NumPy because we imported it as a constant, but we can reimport it and give it a shape that we want.

In [127]:
# Reshape our tensor.
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from our tensors

When dealing with tensors you probably want to be aware of the following attributes:
- Shape
- Rank
- Axis or dimension
- Size

In [128]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

- Now we can use a couple different methods/functions to get some characteristics of our tensors.
- size includes how many elements are in the tensor.
    - size is probably used the least often.

In [129]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

- How to get various attributes of our tensor.

In [130]:
print("Datatype of each element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of each element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing and expanding tensors

- Tensors can be indexed just like Python lists.

In [131]:
# Get the first two elements in each dimension.
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [132]:
# Get the first element from each dimension from each index except for the final one.
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

- Sometimes we may want to change the shape of a tensor:
    - We can add a dimension to a tensor or reshape a tensor.

In [133]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1, 2], [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [134]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [135]:
# Get the last item of each row of our rank 2 tensor.
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

- To add dimensions might not seem helpful now, but will be helpful when we are dealing with data and we need the shapes of the data to match in order to run it through a neural network.

In [136]:
# Add in extra dimension into our rank 2 tensor.
rank_3_tensor = rank_2_tensor[..., tf.newaxis]      # ... means the same as :,:,:,...
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]     # This way you don't have to type out all the :,:,:, etc
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [137]:
# Alternative to tf.newaxis. Same output.
tf.expand_dims(rank_2_tensor, axis=-1)      # "-1" axis means last axis.

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

- If we change the axis in the above example, we can change where the extra dimension is added.

### Manipulating Tensors (Tensor Operations)

##### Basic Operations
    '+', '-', '*', '/'

In [138]:
# You can add values to a tensor using the addition operator.
tensor = tf.constant([[10, 7], 
                      [2, 3]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 13]], dtype=int32)>

- Note that we don't always want to change the original tensor. 

In [139]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  30]], dtype=int32)>

In [140]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-8, -7]], dtype=int32)>

In [141]:
# We can use the TensorFlow built-in functions as well.
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  30]], dtype=int32)>

- You can do regular python operations like + - * / but you can also use some build-in functions.
- If you're dealing with really large tensors, the built-in functions will be faster on a GPU, so go with this.

### Matrix Multiplication

- In machine learning, matrix multiplication is one of the most common operations.
- Until this point, we've been looking at "element-wise" operations.
- Multiplication can be either element-wise or can be what's called a dot product.
    - When multiplying a matrix by a scalar (a single number), we do element wise.
    - When multiplying a matrix by another matrix we do what's called the dot product.
    - Read more on dot products: {{http://matrixmultiplication.xyz/}}

In [142]:
# Matrix Multiplication in TensorFlow
print(tensor)
# Dot product of two tensors.
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 2  3]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114,  91],
       [ 26,  23]], dtype=int32)>

In [143]:
# Product element-wise of two tensors.
print(tensor)
tensor * tensor

tf.Tensor(
[[10  7]
 [ 2  3]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  4,   9]], dtype=int32)>

In [144]:
# Example matrix multiplication from matrixmultiplication.xyz
tensor_1 = tf.constant([[1, 2, 1], [0, 1, 0], [2, 3, 4]])
tensor_2 = tf.constant([[2, 5], [6, 7], [1, 8]])
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [145]:
# To perform matrix multiplication in python with a built-in operator, we use the @ symbol.
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [146]:
# Which matrixes can we multipy together?
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[7, 8], [9, 10], [11, 12]])
# X @ Y       # Results in an error because matrix sizes are incompatible.

- There are two rules that our tensors (or matrices) need to fulfill if we're going to matrix multiply them:
    - The inner dimensions must match.
    - The resulting matrix has the shape of the outer dimensions.

In [147]:
# We can change the shape of Y.
Y = tf.reshape(Y, shape=(2, 3))
print(Y)
print(X.shape)
print(Y.shape)
print(tf.matmul(X, tf.reshape(Y, shape=(2, 3))))
print(tf.matmul(Y, tf.reshape(X, shape=(3, 2))))

tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
(3, 2)
(2, 3)
tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 76 100]
 [103 136]], shape=(2, 2), dtype=int32)


In [148]:
# Can also do this with transpose.
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

- By default, transpose will flip the axis of the matrix, while a regular reshape will maintain the same order of the matrix, but change how they're grouped.

In [149]:
# Try matrix multiplication with transpose rather than reshape.
print(Y.shape)
print(X.shape)
# tf.matmul(tf.transpose(X), Y)

(2, 3)
(3, 2)


##### Dot Product

- Matrix multiplication is also referred to as the dot product.
- You can perform matrix multiplication using:
    - `tf.matmul()`
    - `tf.tesnordot()`

In [150]:
Y = tf.reshape(Y, shape=(3, 2))
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [151]:
# Exmaple of tensordot.
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [152]:
# Perform matrix multiplication between X and Y (transposed).
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [153]:
# Perform matrix multiplication between X and Y (reshaped).
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

- Per the instructor, there are 2 common errors when building neural networks:
    - Tensors are mis-shaped and need to be reshaped.
    - Matrix multiplication works, but something happened during the reshaping process that caused unexpected data (reshape vs transpose).
- That is to say, if something isn't working, it can be really good to use print statements to take a good look at your data and make sure everything is where it should be.

In [154]:
# Check the values of Y, reshape Y and transpose Y
print("Normal Y:")
print(Y, "\n")
print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")
print("Y transponsed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transponsed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


- Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

In [155]:
A = tf.constant([3, 4, 2])
B = tf.constant([[13, 9, 7, 15], [8, 7, 4, 6], [6, 4, 0, 3]])
tf.tensordot(A, B, axes=1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([83, 63, 37, 75], dtype=int32)>

- I just noticed that matmul is really for mutliplying matrices and does not work when multiplying a matrix and a vector.
- If you want to multiply a matrix and a vector, tensordot is the way to go.

### Changing the DataType of a tensor

In [156]:
# Create a new tensor with default datatype (float32)
B = tf. constant([1.7, 7.4])
B.dtype

tf.float32

In [157]:
# Create a new tensor with int32 datatype by using integers with no decimals.
C = tf.constant([7, 10])
C.dtype

tf.int32

- In some circumstances, you may need to run with different data types.
    - 16 bit data types run faster but carry less precision.
- To change, use the cast method.

In [158]:
# Change from float32 to float16 (reduced precision).
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [159]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### Aggregating Tensors

- Aggregating tensors is condensing tensors from multiple values down to a smaller amount of values.

In [160]:
# Get the absolute values.
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [161]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

- Let's go through the following forms of aggregation:
    - Get the minimum.
    - Get the maximum.
    - Get the mean of a tensor.
    - Get the sum of a tensor.

In [162]:
# I will be using this tensor for the exercise.
M = tf.constant(np.random.randint(0, 100, size=50))
M

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([87, 27, 80, 89, 30, 48, 99, 27, 21,  1, 36, 19, 52, 34, 63, 18, 63,
        8, 74, 87, 73, 88, 57, 26,  4, 16, 91, 34, 83, 97, 16, 60, 66, 84,
       62,  7, 20, 66, 20, 51, 40, 60, 10, 32,  5, 37, 18, 33, 96, 34])>

In [163]:
# Get the minimum of a tensor.
tf.reduce_min(M)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [164]:
# Get the maximum of a tensor.
tf.reduce_max(M)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [165]:
# Get the mean of a tensor.
tf.reduce_mean(M)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [166]:
# Get the sum of a tensor.
tf.reduce_sum(M)

<tf.Tensor: shape=(), dtype=int64, numpy=2349>

- TensorFlow tends to put "reduce_" in front of aggregate functions.
- Find the variance and the standard deviation of the tensor before continuing.

In [167]:
M = tf.cast(M, dtype=tf.float32)

In [168]:
# Get the variance of a tensor.
tf.math.reduce_variance(M)

<tf.Tensor: shape=(), dtype=float32, numpy=855.05963>

In [169]:
tf.math.reduce_std(M)

<tf.Tensor: shape=(), dtype=float32, numpy=29.241404>

- Had to cast to a float32 type.
- Some functions in tensor flow require certain types in order to work.
- If you ever get a type error like I did, the best thing to do is look in the documentation and look at the examples and see what types they use.
- Gernally, float 32 is the standard type in tensor flow.

##### Challenge: Find the positional maximum and minimum.

In [170]:
L = tf.constant(np.random.randn(4, 5))
L

<tf.Tensor: shape=(4, 5), dtype=float64, numpy=
array([[-2.21254601, -0.92559599, -0.00317401, -0.28343482, -1.20978237],
       [-0.72225741, -0.07216006,  1.9986215 , -0.05645002,  0.84393116],
       [ 0.26472602, -0.5783191 , -0.00677912, -0.03398538,  0.58780145],
       [ 1.01016466, -0.75746784, -0.11586818, -0.27276934, -0.73359652]])>

In [171]:
print("Position max:", tf.argmax(L, axis=1))
print("Position min:", tf.argmin(L, axis=1))

Position max: tf.Tensor([2 2 4 0], shape=(4,), dtype=int64)
Position min: tf.Tensor([0 0 1 1], shape=(4,), dtype=int64)


### Squeezing a tensor (removing all single dimensions)

- The squeeze function will get rid of extra dimentions of size 1.

In [172]:
# Create a tensor to get started.
tf.random.set_seed(42)
U = tf.constant(tf.random.uniform(shape=[1, 1, 1, 1, 50]))
U

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [173]:
U.shape

TensorShape([1, 1, 1, 1, 50])

- Now with the squeeze function, we can reduce the dimension down so that only those that hold information remain.

In [174]:
U_squeezed = tf.squeeze(U)
U_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [175]:
U_squeezed.shape

TensorShape([50])

- Now the extra empty dimensions are empty.

### One-hot encoding tenosors

- One-hot encoding is a form of numerical encoding.
- Essencially, we take data and spread it out over a larger array based on another variable.
- The example given is like for a photo we have red, gree, and blue values.
    - We can take each of those colors and assign them numbers.
    - Like this, we're doing one-hot encoding for the colors in an image.
- Another example is when dealing with words, depending on the application, we can't always pass words to our neural network. But we can one-hot encode them and the pass them as a number.

In [176]:
# Create a list of indices
some_list = [0, 1, 2, 3, 2]

# One hot encode out list of indices.
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

- Note that every time we see a unique item, we add a column and when we repeat an item we place it in the same column as where we placed it the first time we saw it.

In [177]:
# Specify custom values for one hot encoding.
tf.one_hot(some_list, depth=4, on_value='Yo I love deep learning', off_value='I also like to dance')


<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'Yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'Yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'Yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'Yo I love deep learning'],
       [b'I also like to dance', b'I also like to dance',
        b'Yo I love deep learning', b'I also like to dance']],
      dtype=object)>

- What we do here were we change the default from 0 and 1 to strings is very rarely used in neural networks since we normally want numeric encoding. But still fun to know that this is an option.

In [178]:
# Experimenting a little with the one_hot function.
tf.one_hot(some_list, depth=3)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 1.]], dtype=float32)>

### Trying out more tensor math operations

##### Squaring, log, square root

- Just quickly, you can replicate the numpy arange function in tensorflow with the range function.

In [179]:
# Create a new tensor.
H = tf.range(1, 10)
I = tf.constant(np.arange(1, 10, dtype='int32'))
H, I

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>)

In [180]:
# Square a tensor.
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [181]:
# Square root. (Will error. sqrt method requires non-int type)
# tf.sqrt(H)

In [182]:
# Square root.
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [183]:
# Find the log.
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

- TensorFlow interacts beatufly with the NumPy array.

In [184]:
# Create a tensor directly from a NumPy array.

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [185]:
# Convert out rensor back to a NumPy array.
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [186]:
# convert tensor J to a NumPy array.
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

- If we ever find that there is some functionality that we want to use on a tensor that we can't do in tensorflow, we can always convert to a numpy array, change it and then convert back if we need to.

In [187]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [188]:
# The default types of each are slightly different.
numpy_J = tf.constant(np.array([3, 4, 5]))
tensor_J = tf.constant([3, 4, 5])
numpy_J, tensor_J

(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 4, 5])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>)

- Note that the default types for numpy is usually either int64 or float 64 while the default types for tensorflow is usually int32 and float32.

### Finding access to GPUs

- Again note that numpy arrays must be processed through a CPU while a tensorflow array can be process through a GPU or a TPU.
- If we want to see if we have access to a GPU we can use a special function to check.

In [189]:
# Check GPU access.
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

- If in Google Colab we have free access to google GPUs.
- To configure this:
    - Runtime > Change Runtime Type > Hardware accelerator.
    - Here you can change the option from None to either GPU or TPU.

In [190]:
import tensorflow as tf
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available: 1


In [191]:
!nvidia-smi

/usr/bin/zsh: /home/drew/anaconda3/envs/tf_cert_3/lib/libtinfo.so.6: no version information available (required by /usr/bin/zsh)
Tue Oct 25 14:50:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.76       Driver Version: 515.76       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   57C    P0    26W /  N/A |   4683MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+------

- If you have access to a CUDA-enabled GPU, TensorFlow with automatically use it whenever possible.

### Extra Curriculum

- These are some extra challenges to do to make sure I understand all the content of this chapter.

In [192]:
# Try to use a command we haven't talked about by going through the documentation.
# as_string converts the entire contents of a tensor into strings.
X = tf.constant([1, 2, 3, 4, 5])
tf.as_string(X)

<tf.Tensor: shape=(5,), dtype=string, numpy=array([b'1', b'2', b'3', b'4', b'5'], dtype=object)>

In [193]:
# Calculate your most recent grocery bill with tensors.
groc_list = tf.constant([3.95, 7.88, 15.98, 2.77, 7.11, 6.33])
groc_list_2 = np.random.uniform(1, 20, (15))
print(groc_list_2.shape)
groc_list_2 = groc_list_2.round(decimals=2)
print(groc_list_2)

tf.reduce_sum(groc_list_2)

(15,)
[ 4.78 10.2   1.52  5.53  2.76 11.62  1.47 10.19  7.89 11.33 15.18 13.81
 11.3  15.92 16.94]


<tf.Tensor: shape=(), dtype=float64, numpy=140.44>

In [194]:
# How would you calucate for the month or for the year.
groc_list_jan = np.random.uniform(1, 20, (15))
groc_list_feb = np.random.uniform(1, 20, (15))
groc_list_mar = np.random.uniform(1, 20, (15))
groc_list_master = tf.constant([[groc_list_jan], [groc_list_feb], [groc_list_mar]])
tf.reduce_sum(groc_list_master)

<tf.Tensor: shape=(), dtype=float64, numpy=463.5266170548941>

### TensorFlow 2 quickstart for beginners

- Doing the quickstart guide for beginners from here: 
    - {{https://www.tensorflow.org/tutorials/quickstart/beginner}}

In [195]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.10.0


- Here we are going to use the MNIST dataset which is a dataset of handwritten numbers and we will use this to train a neural network to determine which digit is written.

In [196]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [197]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), 
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])
model

In [198]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.07587474, -0.07740404, -0.75248694,  0.07194675,  0.13117404,
         0.23845708,  0.5949922 ,  0.34162122,  0.56129944,  0.2337757 ]],
      dtype=float32)

In [199]:
tf.nn.softmax(predictions).numpy()

array([[0.07696058, 0.07684298, 0.03912185, 0.08922085, 0.09466478,
        0.1053855 , 0.15052967, 0.1168381 , 0.1455424 , 0.1048933 ]],
      dtype=float32)

In [200]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [201]:
loss_fn(y_train[:1], predictions).numpy()

2.2501302

In [202]:
model.compile(optimizer='adam',
                loss=loss_fn,
                metrics=['accuracy'])

In [203]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 777us/step - loss: 0.2981 - accuracy: 0.9119
Epoch 2/5
1875/1875 [==============================] - 1s 770us/step - loss: 0.1431 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 1s 789us/step - loss: 0.1062 - accuracy: 0.9689
Epoch 4/5
1875/1875 [==============================] - 1s 787us/step - loss: 0.0889 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 1s 775us/step - loss: 0.0740 - accuracy: 0.9765


In [204]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0742 - accuracy: 0.9776 - 258ms/epoch - 823us/step


[0.07416711747646332, 0.9775999784469604]

In [205]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [206]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.2318428e-08, 1.6473855e-08, 3.1926804e-05, 8.9347857e-04,
        3.4310846e-11, 5.9986479e-07, 3.3044140e-12, 9.9906820e-01,
        9.7423776e-07, 4.7094868e-06],
       [1.0436622e-08, 9.5779096e-06, 9.9993908e-01, 3.8101746e-06,
        2.4911851e-14, 5.9991125e-06, 6.2091203e-08, 2.5297809e-12,
        4.1494546e-05, 7.6031514e-11],
       [6.9193725e-08, 9.9632287e-01, 2.5629802e-04, 9.0515168e-06,
        6.0915139e-05, 4.8611078e-06, 3.2811258e-06, 3.0361447e-03,
        3.0436637e-04, 2.2330225e-06],
       [9.9904293e-01, 5.5301550e-09, 1.8553127e-04, 2.1143505e-06,
        1.6330179e-06, 5.6430741e-05, 8.3140432e-05, 1.2813536e-04,
        1.3666349e-07, 4.9984118e-04],
       [2.0341162e-05, 1.0214822e-09, 1.2952049e-04, 1.3217968e-07,
        9.6183187e-01, 7.9696347e-06, 3.8984828e-05, 1.7022662e-04,
        9.0082940e-06, 3.7791826e-02]], dtype=float32)>